import axios from "axios";

//Add product Actions
export const ADD_PRODUCT_REQUESTED = "ADD_PRODUCT_REQUESTED";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const ADD_PRODUCT_RESET = "ADD_PRODUCT_RESET";

//update product actions
export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

// export const DELETE_PRODUCT = 'DELETE_PRODUCT';

// export const DELETE_PRODUCT_SPECIFICATION = 'DELETE_PRODUCT_SPECIFICATION';

/* GET ALL PRODUCTS ACTIONS */
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_ONE_PRODUCT_REQUEST = "GET_ONE_PRODUCT_REQUEST";
export const GET_ONE_PRODUCT_SUCCESS = "GET_ONE_PRODUCT_SUCCESS";
export const GET_ONE_PRODUCT_FAIL = "GET_ONE_PRODUCT_FAIL";

export const ADD_PRODUCT_SPECIFICATION_REQUEST = "ADD_PRODUCT_SPECIFICATION_REQUEST";
export const ADD_PRODUCT_SPECIFICATION_SUCCESS = "ADD_PRODUCT_SPECIFICATION_SUCCESS";
export const ADD_PRODUCT_SPECIFICATION_FAIL = "ADD_PRODUCT_SPECIFICATION_FAIL";
export const ADD_PRODUCT_SPECIFICATION_RESET = "ADD_PRODUCT_SPECIFICATION_RESET";

export const UPDATE_PRODUCT_SPECIFICATION_REQUEST = "UPDATE_PRODUCT_SPECIFICATION_REQUEST";
export const UPDATE_PRODUCT_SPECIFICATION_SUCCESS = "UPDATE_PRODUCT_SPECIFICATION_SUCCESS";
export const UPDATE_PRODUCT_SPECIFICATION_FAIL = "UPDATE_PRODUCT_SPECIFICATION_FAIL";
export const UPDATE_PRODUCT_SPECIFICATION_RESET = "UPDATE_PRODUCT_SPECIFICATION_RESET";

export const GET_ONE_PRODUCT_SPECIFICATION_REQUEST = "GET_ONE_PRODUCT_SPECIFICATION_REQUEST";
export const GET_ONE_PRODUCT_SPECIFICATION_SUCCESS = "GET_ONE_PRODUCT_SPECIFICATION_SUCCESS";
export const GET_ONE_PRODUCT_SPECIFICATION_FAIL = "GET_ONE_PRODUCT_SPECIFICATION_FAIL";
export const GET_ONE_PRODUCT_SPECIFICATION_RESET = "GET_ONE_PRODUCT_SPECIFICATION_RESET";

export const GET_TOP_PRODUCTS_REQUEST = "GET_TOP_PRODUCTS_REQUEST";
export const GET_TOP_PRODUCTS_SUCCESS = "GET_TOP_PRODUCTS_SUCCESS";
export const GET_TOP_PRODUCTS_FAIL = "GET_TOP_PRODUCTS_FAIL";

export const GET_RECENT_PRODUCTS_REQUEST = "GET_RECENT_PRODUCTS_REQUEST";
export const GET_RECENT_PRODUCTS_SUCCESS = "GET_RECENT_PRODUCTS_SUCCESS";
export const GET_RECENT_PRODUCTS_FAIL = "GET_RECENT_PRODUCTS_FAIL";

export const GET_RELATED_PRODUCTS_REQUEST = "GET_RELATED_PRODUCTS_REQUEST";
export const GET_RELATED_PRODUCTS_SUCCESS = "GET_RELATED_PRODUCTS_SUCCESS";
export const GET_RELATED_PRODUCTS_FAIL = "GET_RELATED_PRODUCTS_FAIL";

//update product specification actions
export const DELETE_PRODUCT_SPECIFICATION_REQUEST = "DELETE_PRODUCT_SPECIFICATION_REQUEST";
export const DELETE_PRODUCT_SPECIFICATION_SUCCESS = "DELETE_PRODUCT_SPECIFICATION_SUCCESS";
export const DELETE_PRODUCT_SPECIFICATION_FAIL = "DELETE_PRODUCT_SPECIFICATION_FAIL";
export const DELETE_PRODUCT_SPECIFICATION_RESET = "DELETE_PRODUCT_SPECIFICATION_RESET";
