export const ADD_SLIDER_ITEM_REQUEST = "ADD_SLIDER_ITEM_REQUEST";
export const ADD_SLIDER_ITEM_SUCCESS = "ADD_SLIDER_ITEM_SUCCESS";
export const ADD_SLIDER_ITEM_FAIL = "ADD_SLIDER_ITEM_FAIL";
export const ADD_SLIDER_ITEM_RESET = "ADD_SLIDER_ITEM_RESET";

export const EDIT_SLIDER_ITEM_REQUEST = "EDIT_SLIDER_ITEM_REQUEST";
export const EDIT_SLIDER_ITEM_SUCCESS = "EDIT_SLIDER_ITEM_SUCCESS";
export const EDIT_SLIDER_ITEM_FAIL = "EDIT_SLIDER_ITEM_FAIL";
export const EDIT_SLIDER_ITEM_RESET = "EDIT_SLIDER_ITEM_RESET";

export const DELETE_SLIDER_ITEM_REQUEST = "DELETE_SLIDER_ITEM_REQUEST";
export const DELETE_SLIDER_ITEM_SUCCESS = "DELETE_SLIDER_ITEM_SUCCESS";
export const DELETE_SLIDER_ITEM_FAIL = "DELETE_SLIDER_ITEM_FAIL";
export const DELETE_SLIDER_ITEM_RESET = "DELETE_SLIDER_ITEM_RESET";

export const GET_ALL_SLIDER_ITEMS_REQUEST = "GET_ALL_SLIDER_ITEMS_REQUEST";
export const GET_ALL_SLIDER_ITEMS_SUCCESS = "GET_ALL_SLIDER_ITEMS_SUCCESS";
export const GET_ALL_SLIDER_ITEMS_FAIL = "GET_ALL_SLIDER_ITEMS_FAIL";

export const GET_ONE_SLIDER_REQUEST = "GET_ONE_SLIDER_REQUEST";
export const GET_ONE_SLIDER_SUCCESS = "GET_ONE_SLIDER_SUCCESS";
export const GET_ONE_SLIDER_FAIL = "GET_ONE_SLIDER_FAIL";
