export const CREATE_PRODUCT_REVIEW_REQUEST = "CREATE_PRODUCT_REVIEW_REQUEST";
export const CREATE_PRODUCT_REVIEW_SUCCESS = "CREATE_PRODUCT_REVIEW_SUCCESS";
export const CREATE_PRODUCT_REVIEW_FAIL = "CREATE_PRODUCT_REVIEW_FAIL";
