export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

export const GET_ONE_CATEGORY_REQUEST = "GET_ONE_CATEGORY_REQUEST";
export const GET_ONE_CATEGORY_SUCCESS = "GET_ONE_CATEGORY_SUCCESS";
export const GET_ONE_CATEGORY_FAIL = "GET_ONE_CATEGORY_FAIL";

export const CRAETE_CATEGORIE_REQUEST = "CRAETE_CATEGORIE_REQUEST";
export const CRAETE_CATEGORIE_SUCCESS = "CRAETE_CATEGORIE_SUCCESS";
export const CRAETE_CATEGORIE_FAIL = "CRAETE_CATEGORIE_FAIL";
export const CRAETE_CATEGORIE_RESET = "CRAETE_CATEGORIE_RESET";

export const UPDATE_CATEGORIE_REQUEST = "UPDATE_CATEGORIE_REQUEST";
export const UPDATE_CATEGORIE_SUCCESS = "UPDATE_CATEGORIE_SUCCESS";
export const UPDATE_CATEGORIE_FAIL = "UPDATE_CATEGORIE_FAIL";
export const UPDATE_CATEGORIE_RESET = "UPDATE_CATEGORIE_RESET";

export const GET_MAIN_CATEGORIES_REQUEST = "GET_MAIN_CATEGORIES_REQUEST";
export const GET_MAIN_CATEGORIES_SUCCESS = "GET_MAIN_CATEGORIES_SUCCESS";
export const GET_MAIN_CATEGORIES_FAIL = "GET_MAIN_CATEGORIES_FAIL";
