export const GET_SUB_CATEGORIES_REQUEST = "GET_SUB_CATEGORIES_REQUEST";
export const GET_SUB_CATEGORIES_SUCCESS = "GET_SUB_CATEGORIES_SUCCESS";
export const GET_SUB_CATEGORIES_FAIL = "GET_SUB_CATEGORIES_FAIL";
export const GET_SUB_CATEGORIES_RESEST = "GET_SUB_CATEGORIES_RESEST";

export const CREATE_SUB_CATEGORY_REQUEST = "CREATE_SUB_CATEGORY_REQUEST";
export const CREATE_SUB_CATEGORY_SUCCESS = "CREATE_SUB_CATEGORY_SUCCESS";
export const CREATE_SUB_CATEGORY_FAIL = "CREATE_SUB_CATEGORY_FAIL";
export const CREATE_SUB_CATEGORY_RESET = "CREATE_SUB_CATEGORY_RESET";

export const GET_ONE_SUB_CATEGORY_REQUEST = "GET_ONE_SUB_CATEGORY_REQUEST";
export const GET_ONE_SUB_CATEGORY_SUCCESS = "GET_ONE_SUB_CATEGORY_SUCCESS";
export const GET_ONE_SUB_CATEGORY_FAIL = "GET_ONE_SUB_CATEGORY_FAIL";

export const UPDATE_SUB_CATEGORY_REQUEST = "UPDATE_SUB_CATEGORY_REQUEST";
export const UPDATE_SUB_CATEGORY_SUCCESS = "UPDATE_SUB_CATEGORY_SUCCESS";
export const UPDATE_SUB_CATEGORY_FAIL = "UPDATE_SUB_CATEGORY_FAIL";
export const UPDATE_SUB_CATEGORY_RESET = "UPDATE_SUB_CATEGORY_RESET";
