
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const EMPTY_CART = 'EMPTY_CART';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'
export const RESET_CART='RESET_CART'

//Logged in user cart actions
export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST';
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS';
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL';

export const GET_CART_ITEM_REQUEST='GET_CART_ITEM_REQUEST'
export const GET_CART_ITEM_SUCCESS='GET_CART_ITEM_SUCCESS'
export const GET_CART_ITEM_FAIL = 'GET_CART_ITEM_FAIL'

export const CART_REMOVE_ITEM_REQUEST = 'CART_REMOVE_ITEM_REQUEST';
export const CART_REMOVE_ITEM_SUCCESS = 'CART_REMOVE_ITEM_SUCCESS';
export const CART_REMOVE_ITEM_FAIL = 'CART_REMOVE_ITEM_FAIL';

export const CART_UPDATE_ITEM_REQUEST = 'CART_UPDATE_ITEM_REQUEST';
export const CART_UPDATE_ITEM_SUCCESS = 'CART_UPDATE_ITEM_SUCCESS';
export const CART_UPDATE_ITEM_FAIL = 'CART_UPDATE_ITEM_FAIL';

export const EMPTY_CART_REQUEST='EMPTY_CART_REQUEST'
export const EMPTY_CART_SUCCESS='EMPTY_CART_SUCCESS'
export const EMPTY_CART_FAIL = 'EMPTY_CART_FAIL'

export const USER_CART_SAVE_SHIPPING_ADDRESS_REQUEST='USER_CART_SAVE_SHIPPING_ADDRESS_REQUEST'
 export const USER_CART_SAVE_SHIPPING_ADDRESS_SUCCESS='USER_CART_SAVE_SHIPPING_ADDRESS_SUCCESS'
 export const USER_CART_SAVE_SHIPPING_ADDRESS_FAIL='USER_CART_SAVE_SHIPPING_ADDRESS_FAIL'

