export const DASHBOARD_SIDEBAR_MOBILE_OPEN = "DASHBOARD_SIDEBAR_MOBILE_OPEN";
export const DASHBOARD_SIDEBAR_MOBILE_CLOSE = "DASHBOARD_SIDEBAR_MOBILE_CLOSE";

export const DASHBOARD_SIDEBAR_DESKTOP_TOGGLE = "DASHBOARD_SIDEBAR_DESKTOP_TOGGLE";
