export const GET_BRANDS_REQUEST = "GET_BRAND_REQUEST";
export const GET_BRANDS_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRANDS_FAIL = "GET_BRAND_FAIL";

export const CREATE_BRAND_REQUEST = "CREATE_BRAND_REQUEST";
export const CREATE_BRAND_SUCCESS = "CREATE_BRAND_SUCCESS";
export const CREATE_BRAND_FAIL = "CREATE_BRAND_FAIL";
export const CREATE_BRAND_RESET = "CREATE_BRAND_RESET";

export const GET_ONE_BRAND_REQUEST = "GET_ONE_BRAND_REQUEST";
export const GET_ONE_BRAND_SUCCESS = "GET_ONE_BRAND_SUCCESS";
export const GET_ONE_BRAND_FAIL = "GET_ONE_BRAND_FAIL";

export const UPDATE_BRAND_REQUEST = "UPDATE_BRAND_REQUEST";
export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS";
export const UPDATE_BRAND_FAIL = "UPDATE_BRAND_FAIL";
export const UPDATE_BRAND_RESET = "UPDATE_BRAND_RESET";
