export const GET_ALL_ROLES_REQUEST = "GET_ALL_ROLES_REQUEST";
export const GET_ALL_ROLES_SUCCESS = "GET_ALL_ROLES_SUCCESS";
export const GET_ALL_ROLES_FAIL = "GET_ALL_ROLES_FAIL";

export const GET_ONE_ROLE_REQUEST = "GET_ONE_ROLE_REQUEST";
export const GET_ONE_ROLE_SUCCESS = "GET_ONE_ROLE_SUCCESS";
export const GET_ONE_ROLE_FAIL = "GET_ONE_ROLE_FAIL";

export const ADD_PERMISSION_TO_ROLE_REQUEST = "ADD_PERMISSION_TO_ROLE_REQUEST";
export const ADD_PERMISSION_TO_ROLE_SUCCESS = "ADD_PERMISSION_TO_ROLE_SUCCESS";
export const ADD_PERMISSION_TO_ROLE_FAIL = "ADD_PERMISSION_TO_ROLE_FAIL";
export const ADD_PERMISSION_TO_ROLE_RESET = "ADD_PERMISSION_TO_ROLE_RESET";

export const CREATE_NEW_ROLE_REQUEST = "CREATE_NEW_ROLE_REQUEST";
export const CREATE_NEW_ROLE_SUCCESS = "CREATE_NEW_ROLE_SUCCESS";
export const CREATE_NEW_ROLE_FAIL = "CREATE_NEW_ROLE_FAIL";
export const CREATE_NEW_ROLE_RESET = "CREATE_NEW_ROLE_RESET";

export const REMOVE_PERMISSION_FROM_ROLE_REQUEST = "REMOVE_PERMISSION_FROM_ROLE_REQUEST";
export const REMOVE_PERMISSION_FROM_ROLE_SUCCESS = "REMOVE_PERMISSION_FROM_ROLE_SUCCESS";
export const REMOVE_PERMISSION_FROM_ROLE_FAIL = "REMOVE_PERMISSION_FROM_ROLE_FAIL";
export const REMOVE_PERMISSION_FROM_ROLE_RESET = "REMOVE_PERMISSION_FROM_ROLE_RESET";

export const UPDATE_ROLE_DESCRIPTION_REQUEST = "UPDATE_ROLE_DESCRIPTION_REQUEST";
export const UPDATE_ROLE_DESCRIPTION_SUCCESS = "UPDATE_ROLE_DESCRIPTION_SUCCESS";
export const UPDATE_ROLE_DESCRIPTION_FAIL = "UPDATE_ROLE_DESCRIPTION_FAIL";
