export const GET_HOM_PAGE_CATEGORIES_REQUEST = "GET_HOM_PAGE_CATEGORIES_REQUEST";
export const GET_HOM_PAGE_CATEGORIES_SUCCESS = "GET_HOM_PAGE_CATEGORIES_SUCCESS";
export const GET_HOM_PAGE_CATEGORIES_FAIL = "GET_HOM_PAGE_CATEGORIES_FAIL";

export const GET_NEW_ARRIVAL_REQUEST = "GET_NEW_ARRIVAL_REQUEST";
export const GET_NEW_ARRIVAL_SUCCESS = "GET_NEW_ARRIVAL_SUCCESS";
export const GET_NEW_ARRIVAL_FAIL = "GET_NEW_ARRIVAL_FAIL";

export const GET_TOP_RATED_REQUEST = "GET_TOP_RATED_REQUEST";
export const GET_TOP_RATED_SUCCESS = "GET_TOP_RATED_SUCCESS";
export const GET_TOP_RATED_FAIL = "GET_TOP_RATED_FAIL";

export const GET_HOME_PAGE_BRANDS_REQUEST = "GET_HOME_PAGE_BRANDS_REQUEST";
export const GET_HOME_PAGE_BRANDS_SUCCESS = "GET_HOME_PAGE_BRANDS_SUCCESS";
export const GET_HOME_PAGE_BRANDS_FAIL = "GET_HOME_PAGE_BRANDS_FAIL";

export const GET_SEARCH_CATEGORIES_REQUEST = "GET_SEARCH_CATEGORIES_REQUEST";
export const GET_SEARCH_CATEGORIES_SUCCESS = "GET_SEARCH_CATEGORIES_SUCCESS";
export const GET_SEARCH_CATEGORIES_FAIL = "GET_SEARCH_CATEGORIES_FAIL";

export const GET_SUGGESTED_PRODUCTS_REQUEST = "GET_SUGGESTED_PRODUCTS_REQUEST";
export const GET_SUGGESTED_PRODUCTS_SUCCESS = "GET_SUGGESTED_PRODUCTS_SUCCESS";
export const GET_SUGGESTED_PRODUCTS_FAIL = "GET_SUGGESTED_PRODUCTS_FAIL";
