export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const ADD_USER_ADDRESS_REQUEST = "ADD_USER_ADDRESS_REQUEST";
export const ADD_USER_ADDRESS_SUCCESS = "ADD_USER_ADDRESS_SUCCESS";
export const ADD_USER_ADDRESS_FAIL = "ADD_USER_ADDRESS_FAIL";
export const ADD_USER_ADDRESS_RESET = "ADD_USER_ADDRESS_RESET";

export const USER_ADDRESS_DETAILS_REQUEST = "USER_ADDRESS_DETAILS_REQUEST";
export const USER_ADDRESS_DETAILS_SUCCESS = "USER_ADDRESS_DETAILS_SUCCESS";
export const USER_ADDRESS_DETAILS_FAIL = "USER_ADDRESS_DETAILS_FAIL";
export const USER_ADDRESS_DETAILS_RESET = "USER_ADDRESS_DETAILS_RESET";

export const UPDATE_USER_ADDRESS_REQUEST = "UPDATE_USER_ADDRESS_REQUEST";
export const UPDATE_USER_ADDRESS_SUCCESS = "UPDATE_USER_ADDRESS_SUCCESS";
export const UPDATE_USER_ADDRESS_FAIL = "UPDATE_USER_ADDRESS_FAIL";
export const UPDATE_USER_ADDRESS_RESET = "UPDATE_USER_ADDRESS_RESET";

export const DELETE_USER_ADDRESS_REQUEST = "DELETE_USER_ADDRESS_REQUEST";
export const DELETE_USER_ADDRESS_SUCCESS = "DELETE_USER_ADDRESS_SUCCESS";
export const DELETE_USER_ADDRESS_FAIL = "DELETE_USER_ADDRESS_FAIL";
export const DELETE_USER_ADDRESS_RESET = "DELETE_USER_ADDRESS_RESET";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_REQUEST";
