export const ADD_SLIDER_ITEM_REQUEST = "ADD_SLIDER_ITEM_REQUEST";
export const ADD_SLIDER_ITEM_SUCCESS = "ADD_SLIDER_ITEM_SUCCESS";
export const ADD_SLIDER_ITEM_FAIL = "ADD_SLIDER_ITEM_FAIL";
export const ADD_SLIDER_ITEM_RESET = "ADD_SLIDER_ITEM_RESET";

export const DELETE_SLIDER_ITEM_REQUEST = "DELETE_SLIDER_ITEM_REQUEST";
export const DELETE_SLIDER_ITEM_SUCCESS = "DELETE_SLIDER_ITEM_SUCCESS";
export const DELETE_SLIDER_ITEM_FAIL = "DELETE_SLIDER_ITEM_FAIL";
export const DELETE_SLIDER_ITEM_RESET = "DELETE_SLIDER_ITEM_RESET";
